### ISSUE TITLE
Windows x64 installer looks for MySQL Connector C in wrong Program Files directory

### ISSUE THREAD

**Issue by dagilis** [PyMySQL/mysqlclient-python#142]
Version: 1.3.9
Python version: 3.5.2
Command: _pip install mysqlclient_

Error: 
`
    creating build\temp.win-amd64-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,9,'final',1) -D__version__=1.3.9 "-IC:\Program Files (x86)\MySQL
\MySQL Connector C 6.1\include" -Ic:\python\3.5.2\include -Ic:\python\3.5.2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include
\10.0.10240.0\ucrt" /Tc_mysql.c /Fobuild\temp.win-amd64-3.5\Release\_mysql.obj /Zl
    _mysql.c
    _mysql.c(29): fatal error C1083: Cannot open include file: 'my_config.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python\3.5.2\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dagaz\\AppData\\Local\\Temp\\pip-build-3j2dag3a\\mysqlclient\\setup.py';f=getattr(tokenize, 'open', open)(__
file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dagaz\AppData\Local\Temp\pip-wgjtc53a-record\install-record.txt --single-version-
externally-managed --compile" failed with error code 1 in C:\Users\dagaz\AppData\Local\Temp\pip-build-3j2dag3a\mysqlclient\
`
Expected behavior: x64 platform MySQL Connector C 6.1.9 places itself into _C:\Program Files\_ directory instead of x32 version location _C:\Program Files (x86)\_.

More similar issues on the subject: http://stackoverflow.com/questions/1972259/cannot-open-include-file-config-win-h-no-such-file-or-directory-while-inst

**Comment by dagilis** [comment]
Wworkaround: I've copied _c:\Program Files\MySQL\MySQL Connector C 6.0.2\_ directory to _c:\Program Files (x86)\MySQL\MySQL Connector C 6.1\_ and it worked fine.

**Comment by methane** [comment]
You can't pip install from source.
You need to manually configure site.cfg file.

**Comment by ba11ak** [comment]
The workaround worked for me. Thanks a lot, @dagilis !

**Comment by sajib-4414** [comment]
Install python 3.6.5 for windows,
then 
pip install mysqlclient==1.3.12

**Comment by AMDphreak** [comment]
In my case, I had to copy or link (using [link shell extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html)) the x64 version of "C Connector" to the x86 folder:

- [ ] Install [link shell extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html).
- [ ] Navigate to "C:\Program Files\MySQL\" then right click on "MySQL Connector C 6.1" and click `Pick Link Source`
- [ ] Navigate to "C:\Program Files (x86)\MySQL\" and `Drop Link As...` > `Junction`
A Junction is a duplicate reference in the file system to a folder. Creating a second junction reclassifies the original folder a junction as well, but they are both authentic references to the same folder, and so, unlike symbolic links, they will work with scripts, because they are real, and are implemented on the file system level.
- [ ] Then, if the connector you have installed is a different version and you want to try to force it to work with a non-compatible script, rename it to match the folder mentioned in the error message. For example...
  >  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726
  > \bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,13,'final',0) -D__version__=1.3.13 "-I **`C:\Program Files (x86)\MySQL\MySQL Connector C 6.1`** \include" "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visu...

### If you can't find the x64 C connector...

- [ ] Download `mysql-installer-web-community-8.0.12.0.msi` from their website:
[https://dev.mysql.com/downloads/installer/](https://dev.mysql.com/downloads/installer/)
- [ ] Run the Installer, and click the `Add` button on the right, then locate the `Connector C 6.1 x64`

The C++ Connector has C compatible header files, but hard-linking to it does not work, as explained here: [https://dev.mysql.com/downloads/connector/c/](https://dev.mysql.com/downloads/connector/c/)

You cannot install the x86 version of the C connector alongside the x64 version. The installer does not permit this.

Crappy Oracle coders :(

**Comment by methane** [comment]
Connector 6.1 can't connect to MySQL 8.

I'm waiting MariaDB Connector.  It supports sha256_password without OpenSSL.  It uses SChannel and  WinCrypto.
https://github.com/MariaDB/mariadb-connector-c/blob/9c3658731f7db66c5b2ad6f941e6c1b13de2b362/plugins/auth/sha256_pw.c#L236-L261

I think caching_sha2_password can be supported in same way.

**Comment by AMDphreak** [comment]
> Connector 6.1 can't connect to MySQL 8.
> 
> I'm waiting MariaDB Connector. It supports sha256_password without OpenSSL. It uses SChannel and WinCrypto.
> https://github.com/MariaDB/mariadb-connector-c/blob/9c3658731f7db66c5b2ad6f941e6c1b13de2b362/plugins/auth/sha256_pw.c#L236-L261
> 
> I think caching_sha2_password can be supported in same way.

Read my post. This problem has nothing to do with inability to connect two parts. It has everything to do with the installer/compiler looking for resources in the wrong directory due to the user choosing to install an x64 version of MySQL Connector 6.1 instead of the x86 version. This problem has been diagnosed and solved at length.

**Comment by carloshm91** [comment]
> Install python 3.6.5 for windows,
> then
> pip install mysqlclient==1.3.12

but why not work on mysqlclient 1.3.13?

**Comment by AMDphreak** [comment]
> but why not work on mysqlclient 1.3.13?
Don't know. Check the [docs](https://libraries.io/pypi/mysqlclient) for installing that version.
