### ISSUE TITLE
IntegrityError raised twice; from cursor.execute() and  cursor.close()

### ISSUE THREAD

**Issue by azurit** [PyMySQL/mysqlclient-python#282]
I'm trying this only on version 1.3.7 because i'm unable to run newer version (getting 'undefined symbol: OPENSSL_add_all_algorithms_noconf' after import, MariaDB 10.1), one i'm using was installed as original package from Debian 9.

When using SSCursor or SSDictCursor, i'm getting IntegrityError on 'execute' command AND the same IntegrityError error also on cursor close(). 100% reproducable, also see few comments in the code:

```
import MySQLdb

db_conn = MySQLdb.connect(host="localhost", user="user", passwd="password", db="database")
db_conn.autocommit(True)
db_curr = db_conn.cursor(MySQLdb.cursors.SSDictCursor)
# uncoment this to 'fix' the error
#db_curr = db_conn.cursor()
try:
        db_curr.execute("CREATE TABLE `test` (test VARCHAR(255) UNIQUE) ENGINE=InnoDB")
except:
        pass
# this is interesting, the error only appears if there is any SELECT before
db_curr.execute("SELECT * FROM `test`")
mysql_result = db_curr.fetchall()
try:
        db_curr.execute("INSERT INTO `test` SET test='test'")
        db_curr.execute("INSERT INTO `test` SET test='test'")
except MySQLdb.IntegrityError:
        print "catched IntegrityError"
db_curr.close()
db_conn.close()
```

Output:

```
catched IntegrityError
Traceback (most recent call last):
  File "test_db.py", line 19, in <module>
    db_curr.close()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 91, in close
    while self.nextset():
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 138, in nextset
    self.fetchall()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 474, in fetchall
    r = self._fetch_row(0)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 351, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'test' for key 'test'")
```

**Comment by methane** [comment]
The error is from MariaDB, not PyMySQL.
Try `SELECT * FROM test` in mysql cli.

**Comment by azurit** [comment]
I don't understand, what should i see? How this could be a MariaDB bug?

**Comment by azurit** [comment]
Did you even read my bug report and code? I wasn't talking about duplicate entry but about mysqlclient throwing the same error twice - and, as you can see in the traceback, the second one is thrown by 'db_curr.close()'.

**Comment by methane** [comment]
> Did you even read my bug report and code? I wasn't talking about duplicate entry but about mysqlclient throwing the same error twice - and, as you can see in the traceback, the second one is thrown by 'db_curr.close()'.

I'm sorry, I didn't.  I've tired to maintain this project because most issue reports are not issue report.
I'm not good at English and reading issue report seriously is tough job to me.  I can't use my time to read issue reports anymore.

In your case:

* Issue title doesn't mention IntegrityError is raised twice -- raised on close is not a bug because SSCursor evaluates response lazy.
* You used Python 2.  You used old version of mysqlclient.  (Link error is your environment problem -- you linked two version of OpenSSL in one Python process.  You need to unify OpenSSL)
* Your output contains only one traceback while IntegrityError is raised twice.
* I (and my company) don't use SSCursor.  Django and SQLAlchemy don't use it.  SSCursor is helpful only when fetching large dataset.  But no one uses SSCursor by default.

Because of these, I don't have motivation to read your issue seriously.

After reading your report again, I think it's bug of SSCursor implementation.  
SSCursor may have more bugs; it's more complicated than Cursor, and everyone uses Cursor.  SSCursor is used only for limited case.

**Comment by methane** [comment]
In SSCursor, mysqlclient uses `mysql_use_result`, then `mysql_fetch_row`.

https://dev.mysql.com/doc/refman/5.6/en/mysql-use-result.html
https://dev.mysql.com/doc/refman/5.6/en/mysql-fetch-row.html

`mysql_fetch_row` document says: "Errors are not reset between calls to mysql_fetch_row()"

But in this case, it seems error is not reset between `mysql_use_result` and `mysql_fetch_row`.
mysqlclient-python can't distinguish two error is same or not.  I think it's bug of C library implementation.

What client library you used to build mysqlclient-python?  mariadbclient? mysqlclient? and what exact version?

**Comment by methane** [comment]
And please don't hide first IntegrityError traceback.  It's very important.
You can use `logging.exception("Catched IntegrityError")` instead of print.

**Comment by azurit** [comment]
I don't know how was package compiled, i'm using original Debian 9 package or mysqlclient:
https://packages.debian.org/stretch/python-mysqldb

By the way, this bug is NOT present in original python-MySQLdb library (i was using it before without any problems with the same code).

Thank you for your time.

**Comment by methane** [comment]
> I don't know how was package compiled, i'm using original Debian 9 package or mysqlclient:
> https://packages.debian.org/stretch/python-mysqldb

The page says "dep: libmariadbclient18 (>= 5.5.36)".  So you use libmariadbclient.

https://packages.debian.org/stretch/libmariadbclient18

If you're using newest version of it, it should be 10.1.26.  Thanks.


> 
> By the way, this bug is NOT present in original python-MySQLdb library (i was using it before without any problems with the same code).

So what?  Do you mean "YOU breaked! YOU implemented a BUG!"?
Maybe, you're right.  But note that I fixed more bugs, and compatibility issues.  I used much time and energy.
Additionally, it's possible the bug is in libmariadbclient, not mysqlclient-python.
You didn't debug it yet.  You don't know where the bug in and you didn't use your time and energy to debug it.  **I** will use my time and energy to debug it.

I'm not paid from Oracle or you.  I'm a volunteer maintainer.

**Comment by methane** [comment]
I can't reproduce it on Ubuntu (libmariadbclient==10.2.9).

**Comment by azurit** [comment]
Sorry, you misunderstood me, i didn't want to point on you making bugs and make you angry, i just wanted to say it's a new bug.

**Comment by methane** [comment]
Can you confirm what version of libmariadbclient do you use?  Is it "10.1.26-0+deb9u1"?

I confirmed it is not reporducible with "libmariadbclient-dev/bionic-updates,bionic-security,now 1:10.1.34-0ubuntu0.18.04.1 amd64 [installed]" on Ubuntu 18.04.

I read all changelog between 10.1.26 and 10.1.34.  But I can't find any changelog relating this issue.

**Comment by azurit** [comment]
I have 10.2.14+maria~stretch (probably because i had installed MariaDB 10.2 in the past but i downgraded to 10.1). I can try to downgrade also this library if you think it will helps.

**Comment by azurit** [comment]
Ok so, everything is upgraded/downgraded, now i have 10.1.37+maria-1~stretch and it's still doing the same.

**Comment by azurit** [comment]
Try to run my script twice without droping table test.

**Comment by methane** [comment]
> * without droping table test.*

Hah!  I waste several hours.  I tested some MySQL / MariaDB versions!!!

**Comment by azurit** [comment]
Well, sorry but i wasted about a week trying to figure out why is this happening in our application and creating most simple script which is able to reproduce it..

**Comment by methane** [comment]
I confirmed this bug is *old*.  MySQL-python-1.2.5 has same behavior.

**Comment by azurit** [comment]
Thank you very much for your time and energy!
