### ISSUE TITLE
Cannot import _mysql_exceptions

### ISSUE THREAD

**Issue by larsskj** [PyMySQL/mysqlclient-python#362]
We have been using mysqlclient with Python3 for a long time - more precisely with Apache Airflow.
However, with release 1.4.0, _mysql and _mysql_exceptions was moved to MySQLdb in pull request #293. I cannot find any explanations for this move - but it breaks our code?
Airflow is Python3 only, and newer Airflow distributions (Docker/Kubernetes) includes 1.4.x instead of 1.3.x and breaks code depending on _mysql_exceptions.
We cannot install and use MySQLdb as it is Python2 only. Also, it would require modifications of the standard Airflow image.
This decision makes mysqlclient Python2 only as well in some regards - why?

**Comment by methane** [comment]
When you are using names starting with `_`, your should not expect any backward compatibility.
Why don't you fix your code?

I moved them because I don't want put files in `site-packages` directly.  All files in `MySQLdb` is more make sense.
And if someone want to build mysqlclient to use dll on Windows, they can put the dll in MySQLdb, not site-packages.
If they put dll in site-packages, it will conflict with MySQL Connector/Python.

**Comment by larsskj** [comment]
Thanks for the explanation.
We will fix the code - we have decided to stop using mysqlclient.

**Comment by weibangtuo** [comment]
`_mysql_exceptions` and `MySQLdb._mysql_exceptions` have been renamed to `MySQLdb._exceptions`  at my mysqlclient==2.1.1 version. You can change code to new namespace if you can access the code. 

But I can't access the code, and I don't even know what made the mistake.
I solved it this way.
```
# show location of mysqlclient
python3 -m pip show mysqlclient
cd /usr/local/lib/python3.*/site-packages
echo 'from MySQLdb._exceptions import *' > _mysql_exceptions.py
# test
python3 -c 'import _mysql_exceptions'
```

**Comment by methane** [comment]
> But I can't access the code, and I don't even know what made the mistake.

Importing it is mistake. Do not use modules with `_` prefix.
