### ISSUE TITLE
 Clarify license

### ISSUE THREAD

**Issue by stephan-hof** [PyMySQL/mysqlclient-python#425]
Hi, this is a follow up of this comment:
https://github.com/PyMySQL/mysqlclient-python/issues/58#issuecomment-402891157

From my understand this library is under dual license.
It would be great that this fact is more prominent visible.

My suggestion would be:

* Rename LICENSE to LICENSE.GPL-2.0
* Add a second file called LICENSE.CNRI with the contents of this file https://opensource.org/licenses/pythonpl.php
* Changing  MANIFEST.in to include both in the source tarball
* Changing `metadata.cfg`
    * Adding `License :: OSI Approved :: Python License (CNRI Python License)` to `classifiers`
    * Set `license` to `GPLv2, CNRI`

**Comment by methane** [comment]
I don't understand how MySQL-python is licensed.

I am not lawer, but as far as I am reading https://opensource.org/licenses/pythonpl.php ,
this license is only for Python.  Other OSS project can not use the license.

**Comment by stephan-hof** [comment]
I wrote this because of this post from the original author:
https://sourceforge.net/p/mysql-python/discussion/70460/thread/9ae42ab5/
> Originally MySQLdb had a license based on the old Python license, i.e. the CNRI license, which is essentially BSD-ish. Later, because MySQL uses a GPL license, GPL v2 was added. However, it's up to you which license to use on MySQLdb-1.2

There is also:
* https://github.com/PyMySQL/mysqlclient-python/blob/master/INSTALL.rst#license
* https://github.com/PyMySQL/mysqlclient-python/issues/58#issuecomment-147905478

indicating a dual license.

I agree with you. It is not the CNRI directly which is only for python.
I think the license text meant is this here: https://sourceforge.net/p/mysql-python/code/ci/57319a392808fbcb0fd3029fad67be9d15a24a37/tree/mysql/license.py

In that case the following could be done:

* Rename LICENSE to LICENSE.GPL-2.0
* Add a second file called LICENSE.alt (for alternative) with the contents of license.py
* Changing MANIFEST.in to include both in the source tarball
* Changing metadata.cfg
    *  Adding `License :: OSI Approved :: BSD License`, because it is very close to it.
    * Set license to `GPLv2, BSD-ish`

**Comment by romainr** [comment]
+1

This would help to promote open source projects that give an out of the box connection with MySql (e.g. Hue SQL)

**Comment by methane** [comment]
> I agree with you. It is not the CNRI directly which is only for python.
> I think the license text meant is this here: https://sourceforge.net/p/mysql-python/code/ci/57319a392808fbcb0fd3029fad67be9d15a24a37/tree/mysql/license.py

license.py seems GPL 2.0.

> Rename LICENSE to LICENSE.GPL-2.0
> Add a second file called LICENSE.alt (for alternative) with the contents of license.py

"GPL v2 or GPL v2" is not dual license.

**Comment by metzen** [comment]
> license.py seems GPL 2.0.

I do not think that this evaluation is correct. The license in this file appears to be BSD-like, in that it only carries "notice" requirements without the additional burdens of mandatory source distribution imposed by GPL 2.0 (when required).

Does that potentially change the manner in which this issue is evaluated, or would the project still be considered to be singly licensed under GPL v2?

**Comment by StevenMapes** [comment]
This packages license is 10% GPL2 which means any project using it is GPL2 as installing the package means you are extending the package and thus must use the same license and publish the source code of any project using the package.  If it were MIT, BSD, OSI Approved then it would now. LGPL potentially would also not require it unless modifying the package self.

In short do not use this package for anything outside of public GPL compatible projects

**Comment by mschoettle** [comment]
I am tasked with reviewing our open source dependencies and ensuring that we are compliant with each license.

Based on what I see, the license is actually [`GPL-2.0-or-later`](https://spdx.org/licenses/GPL-2.0-or-later.html) and not [`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html). The standard license header contains the "either version 2, or (at your option) any later version":

https://github.com/PyMySQL/mysqlclient/blob/a958c5fa45d3833e9fbf31ce0c4a461782929067/src/MySQLdb/_mysql.c#L4-L5

This is good because it allows it to be used with future GPL versions: 

* https://www.gnu.org/licenses/identify-licenses-clearly.en.html
* https://en.wikipedia.org/wiki/License_compatibility

Would it be possible to set the license identifier to `GPL-2.0-or-later` in the package metadata? This is also suggested by GitHub: https://choosealicense.com/licenses/gpl-2.0/ (right-hand side "How to apply this license").

**Comment by methane** [comment]
@mschoettle Thank you for your suggestion. Please check #722.

**Comment by mschoettle** [comment]
Thanks a lot @methane!

In general, an LGPL license would be somewhat easier since it distinguishes between modification of the library and using the library. But it might not be that easy to change it now.
