### ISSUE TITLE
License Offerings

### ISSUE THREAD

**Issue by alexggordon** [PyMySQL/mysqlclient-python#58]
Hello! Recently, I started working through building my own Python 3 support for MySQLdb. However, before I started doing so I had come across a post by the original author, @farcepest on [Sourceforge](http://sourceforge.net/p/mysql-python/discussion/70460/thread/9ae42ab5) about how users could optionally use the [CNRI](http://opensource.org/licenses/pythonpl.php) license (I've copied the post [here](https://gist.github.com/alexggordon/cad0d1cc5e876cae513e) in case it disappears for some reason).

I think given your work on MySQLdb, and given that @farcepest originally offered it, I think it would be really cool if you would extend that offer onto the users of mysqlclient-python.

In @farcepest's post, he mentions that this CNRI offering applies to versions of MySQLdb lower than 1.3, (mysqlclient-python forked MySQLdb at version 1.2).

The gist of the offering would be allowing the users to choose either the CNRI license, or GPL2. That said though that could get a little confusing, but is a really nice choice I think. 

Do you have any thoughts on the issue?

**Comment by methane** [comment]
About **using** MySQLdb as `import MySQLdb`, your app can select any license you want.

About **distributing** MySQLdb, I don't think dual licensing doesn't have meaning since MySQLdb
requires libmysqlclient and libmysqlclient is distributed on GPLv2.

Is this enough for you?

**Comment by JukkaHonkola** [comment]
Is this correct? I see that the LICENCE file defines the licence as GPLv2, not LGPL. Thus, in my understanding any program that imports MySQLdb would also be GPLv2. This would cause any program using MySQLdb to be licenced under GPLv2.

**Comment by methane** [comment]
Yes.  MySQLdb uses MySQL Connector/C.  It's GPLv2.

This is not a problem when you use MySQL-python on server.
You don't required to make your server-side application open to end users. (Sinse GPL is not AGPL.)

**Comment by fredigato** [comment]
I see this issue is marked as closed, but maybe it shouldn't. There is a MySQL Connector/C version that is LGPL and the new MariaDB Connector/C is LGP by default, so this option should be considered for the python library too.

**Comment by methane** [comment]
To change license, acknowledgement of original owner (@farcepest) is required.
Since he is inactive for very long, I think it's very hard.

Since I'm not a lawyer, I may be wrong.  But I don't like to pay time and power for licensing issue.

**Comment by antoncohen** [comment]
Sorry to dig up an old issue. The original MySQLdb is dual licensed, GPLv2 and Old Python license (CNRI Python License).

MySQL is GPLv2, but it has a [licensing exception](https://www.mysql.com/about/legal/licensing/foss-exception/) for FOSS software, with CNRI Python License listed as one of the allowed licenses. This is really important, because it allows MySQL client wrapper libraries (like mysqlclient-python) to be licensed under a liberal license, and then projects like Django can use the wrapper libraries.

**It looks like mysqlclient-python is still licensed under the CNRI Python License, as seen at the bottom of [INSTALL.rst](https://github.com/PyMySQL/mysqlclient-python/blob/master/INSTALL.rst#license).**

It would be nice if this information what in a more prominent place, it would be extra nice if PyPI listed it as one of the licenses.
