### ISSUE TITLE
incompatible behavior with MySQL-python

### ISSUE THREAD

**Issue by pypeng** [PyMySQL/mysqlclient-python#92]
https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/cursors.py#L67

This line of change makes it hard for us to replace MySQL-python with mysqlclient-python.

We have lots of inhouse code like this:

`cursor.connection.rollback()`

The commit changed proxy into ref, these code have to be changed into:

`conn = cursor.connection()`
`conn.thread_id()`

what is the reason behind this commit?

**Comment by methane** [comment]
> what is the reason behind this commit?

MySQL-python doesn't document the API.  It had been exposed unintentionally.

I doesn't remember the reason.  But `self.connection = None` was so important to break
unintentionally exposed API.

I don't want to rollback the change, since it may breaks code using current mysqlclient.

> We have lots of inhouse code like this:
> cursor.connection.rollback()
> The commit changed proxy into ref, these code have to be changed into:
> conn = cursor.connection()
> conn.thread_id()

It seems easy enough.
But I recommend you to not using `cursor.connection`.  Just use `connection`.

**Comment by methane** [comment]
> But I recommend you to not using cursor.connection. Just use connection.

Because I want to remove weakref in the future.
`Cursor.connection` is not documented, and will be changed in the future.

**Comment by pypeng** [comment]
> MySQL-python doesn't document the API. It had been exposed unintentionally.

It's been documented here:
https://github.com/PyMySQL/mysqlclient-python/blob/master/doc/user_guide.rst#mysql-c-api-function-mapping

> I don't want to rollback the change, since it may breaks code using current mysqlclient.
sadly agree. I'll see what i can do to migrate to mysqlclient-python

**Comment by methane** [comment]
> It's been documented here:
> https://github.com/PyMySQL/mysqlclient-python/blob/master/doc/user_guide.rst#mysql-c-api-function-mapping

Where?

Do you mean `Cursor.connection` or `connection.rollback()`?

**Comment by methane** [comment]
>> I don't want to rollback the change, since it may breaks code using current mysqlclient.

> sadly agree. I'll see what i can do to migrate to mysqlclient-python

I don't think there are many users of current `Cursor.connection()`, since no one report the
incompatibility before you.

I'm thinking about removing weakref and making `cursor.connection` real connection object in next release.
Maybe, I'll renaming it to `corsor._conn` and `Cursor.connection` is property returns connection and
raise DeprecatedWarning.

**Comment by pypeng** [comment]
> I'm thinking about removing weakref and making cursor.connection real connection object in next release.

+1

> Where?
> 
> Do you mean Cursor.connection or connection.rollback()?

My mistake. But Cusor.connection is a public attribute, it should be Cursor's public api.
